/** Preset interaction verbs/phrases for canvas connections (searchable). */
export const COMMON_INTERACTION_LABELS: string[] = [
  "interacts with",
  "talks to",
  "listens to",
  "argues with",
  "confronts",
  "fights",
  "embraces",
  "kisses",
  "avoids",
  "stares at",
  "warns",
  "threatens",
  "helps",
  "protects",
  "betrays",
  "lies to",
  "confides in",
  "gives to",
  "takes from",
  "follows",
  "leads",
  "notices",
  "ignores",
  "reunites with",
  "parts from",
  "negotiates with",
  "works with",
  "competes with",
  "teaches",
  "learns from",
  "comforts",
  "mourns with",
  "dances with",
  "trades with",
  "interrogates",
  "rescues",
  "pursues",
  "hides from",
  "reveals to",
  "witnesses",
];
